services:
  # SERVICIO 1: Base de Datos
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=admksf
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=S4br1n4b0t0n4
    ports:
      - "5432:5432"

  # SERVICIO 2: Django + Angular
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=admksf
      - DB_USER=admin
      - DB_PASSWORD=S4br1n4b0t0n4
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=B0k4v4S4l1rc@mp30n
      - DJANGO_DEBUG=True
    command: gunicorn --bind 0.0.0.0:8000 backend_core.wsgi:application

volumes:
  postgres_data:
